# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1GYEa8Hm3buD83bhSW6sqzrJuMgQQst
"""



import numpy as np
marks=[10,20,30,40,50,60]
mean=np.mean(marks)
print(mean)

import numpy as np
marks=[10,20,30,40,50,60]
median=np.median(marks)
print(median)

import numpy as np
marks=[10,20,30,40,50,60]
v=np.var(marks)
print(v)

import numpy as np
marks=[10,20,30,40,50,60]
sp=np.std(marks)
print(sp)

import statistics as np
marks=[10,20,30,40,50,60,70,80,80]
mode=np.mode(marks)
print(mode)